#!/bin/bash
# example file to be used with --hookdir
#
# 343894: script from q-funk.

# Depends on CDBS module in debian/rules:
# include /usr/share/cdbs/1/rules/utils.mk

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

echo "I: checking for missing files."
cd "$BUILDDIR"/*/debian/..

fakeroot debian/rules list-missing
#EOF
